fix: adjust paths

diff --git a/.github/workflows/maven-core-cm.yml b/.github/workflows/maven-core-cm.yml
--- a/.github/workflows/maven-core-cm.yml
+++ b/.github/workflows/maven-core-cm.yml
@@ -57,18 +57,18 @@ jobs:
           testsuite/scripts/run-suite.sh
       - name: Run Spotless (Maven plugin)
         run: |
-          mvn -B spotless:apply -P!enforcer --file pom.xml
+          mvn -B spotless:apply -P!enforcer --file testsuite/org.eclipse.lyo.testsuite.build/pom.xml
           if [ -z "$(git status --porcelain)" ]; then
             echo "Spotless PASS"
           else
-            echo "Spotless FAIL; run `mvn validate -Pspotless` locally" >&2
+            echo "Spotless FAIL; run `mvn validate -Pspotless --file org.eclipse.lyo.testsuite.build/pom.xml` locally" >&2
           fi
       - name: Run OpenRewrite (Maven plugin)
         # package is needed due to ANTLR and net.oauth.core processing steps
         run: |
-          mvn -B package org.openrewrite.maven:rewrite-maven-plugin:run spotless:apply -DskipTests -P'!enforcer' --file pom.xml
+          mvn -B package org.openrewrite.maven:rewrite-maven-plugin:run spotless:apply -DskipTests -P'!enforcer' --file testsuite/org.eclipse.lyo.testsuite.build/pom.xml
           if [ -z "$(git status --porcelain)" ]; then
             echo "rewrite PASS"
           else
-            echo "rewrite FAIL; run `mvn org.openrewrite.maven:rewrite-maven-plugin:run` locally" >&2
+            echo "rewrite FAIL; run `mvn org.openrewrite.maven:rewrite-maven-plugin:run` locally --file org.eclipse.lyo.testsuite.build/pom.xml" >&2
           fi
