Upgrade Lyo dependency to 7.0.0.Beta3 (#389)
* upgrade testsuite to latest published Lyo prerelease

* Apply OpenRewrite Maven plugin update

* Clarify local formatting commands

diff --git a/.github/workflows/maven-core-cm.yml b/.github/workflows/maven-core-cm.yml
--- a/.github/workflows/maven-core-cm.yml
+++ b/.github/workflows/maven-core-cm.yml
@@ -75,7 +75,7 @@ jobs:
           if [ -z "$(git -C testsuite/ status --porcelain)" ]; then
             echo "Spotless PASS"
           else
-            echo "Spotless FAIL; run 'mvn -B --settings .mvn/settings.xml spotless:apply -P!enforcer --file org.eclipse.lyo.testsuite.build/pom.xml' locally" >&2
+            echo "Spotless FAIL; from the testsuite repository root run: mvn -B --settings .mvn/settings.xml spotless:apply -P'!enforcer' --file org.eclipse.lyo.testsuite.build/pom.xml" >&2
             exit 1
           fi
       - name: Run OpenRewrite (Maven plugin)
@@ -84,6 +84,6 @@ jobs:
           if [ -z "$(git -C testsuite/ status --porcelain)" ]; then
             echo "rewrite PASS"
           else
-            echo "rewrite FAIL; run 'mvn -B --settings .mvn/settings.xml org.openrewrite.maven:rewrite-maven-plugin:run spotless:apply -DskipTests -P!enforcer --file org.eclipse.lyo.testsuite.build/pom.xml' locally" >&2
+            echo "rewrite FAIL; from the testsuite repository root run: mvn -B --settings .mvn/settings.xml org.openrewrite.maven:rewrite-maven-plugin:run spotless:apply -DskipTests -P'!enforcer' --file org.eclipse.lyo.testsuite.build/pom.xml" >&2
             exit 1
           fi
