fix: lint adjust

diff --git a/.github/workflows/maven-core-cm.yml b/.github/workflows/maven-core-cm.yml
--- a/.github/workflows/maven-core-cm.yml
+++ b/.github/workflows/maven-core-cm.yml
@@ -61,7 +61,8 @@ jobs:
           if [ -z "$(git -C testsuite/ status --porcelain)" ]; then
             echo "Spotless PASS"
           else
-            echo "Spotless FAIL; run `mvn validate -Pspotless --file org.eclipse.lyo.testsuite.build/pom.xml` locally" >&2
+            echo "Spotless FAIL; run 'mvn validate -Pspotless --file org.eclipse.lyo.testsuite.build/pom.xml' locally" >&2
+            exit 1
           fi
       - name: Run OpenRewrite (Maven plugin)
         run: |
@@ -69,5 +70,6 @@ jobs:
           if [ -z "$(git -C testsuite/ status --porcelain)" ]; then
             echo "rewrite PASS"
           else
-            echo "rewrite FAIL; run `mvn org.openrewrite.maven:rewrite-maven-plugin:run` locally --file org.eclipse.lyo.testsuite.build/pom.xml" >&2
+            echo "rewrite FAIL; run 'mvn org.openrewrite.maven:rewrite-maven-plugin:run; locally --file org.eclipse.lyo.testsuite.build/pom.xml" >&2
+            exit 1
           fi
