build: lint & updates (#184)

diff --git a/.github/workflows/maven-core-cm.yml b/.github/workflows/maven-core-cm.yml
--- a/.github/workflows/maven-core-cm.yml
+++ b/.github/workflows/maven-core-cm.yml
@@ -8,8 +8,8 @@ on:
     branches: [master, main]
   pull_request:
     branches: [master, main]
-  # schedule:
-  #   - cron: "30 4 * * 5" # catch SNAPSHOT breaking changes
+  schedule:
+    - cron: "30 4 * * 5" # catch SNAPSHOT breaking changes
   merge_group:
   workflow_dispatch:
 
@@ -38,9 +38,9 @@ jobs:
       - uses: actions/cache@v4
         with:
           path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          key: ${{ runner.os }}-${{ matrix.jdk }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
-            ${{ runner.os }}-maven-
+            ${{ runner.os }}-${{ matrix.jdk }}-maven-
       - name: Build RefImpl
         run: |
           # disable basic auth
@@ -55,3 +55,21 @@ jobs:
           sleep 20
           >&2 echo "Done sleeping"
           testsuite/scripts/run-suite.sh
+      - name: Run Spotless (Maven plugin)
+        run: |
+          mvn -B spotless:apply -P!enforcer --file testsuite/org.eclipse.lyo.testsuite.build/pom.xml
+          if [ -z "$(git -C testsuite/ status --porcelain)" ]; then
+            echo "Spotless PASS"
+          else
+            echo "Spotless FAIL; run 'mvn validate -Pspotless --file org.eclipse.lyo.testsuite.build/pom.xml' locally" >&2
+            exit 1
+          fi
+      - name: Run OpenRewrite (Maven plugin)
+        run: |
+          mvn -B org.openrewrite.maven:rewrite-maven-plugin:run spotless:apply -DskipTests -P'!enforcer' --file testsuite/org.eclipse.lyo.testsuite.build/pom.xml
+          if [ -z "$(git -C testsuite/ status --porcelain)" ]; then
+            echo "rewrite PASS"
+          else
+            echo "rewrite FAIL; run 'mvn org.openrewrite.maven:rewrite-maven-plugin:run; locally --file org.eclipse.lyo.testsuite.build/pom.xml" >&2
+            exit 1
+          fi
